version: "3"
services:
  rest-number:
    image: "justier/number-microservice:1.0.0-SNAPSHOT"
    ports:
      - "8701:8701"
  rest-book:
    image: "justier/book-microservice:1.0.0-SNAPSHOT"
    ports:
      - "8702:8702"
    environment:
      - NUMBER_PROXY_MP_REST_URL=http://rest-number:8701
